### Data Preprocessing

In [77]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [78]:
df= pd.read_csv('C:\\Users\\HP\\Downloads\\Python ML\\Artificial Neural Network\\Churn_Modelling.csv')

In [79]:
df.shape

(10000, 14)

In [80]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [81]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [82]:
X= df.iloc[:,3:-1].values
y= df.iloc[:,-1].values

In [83]:
X[:5,:]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [84]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [85]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X_1= LabelEncoder()
X[:,1]= labelencoder_X_1.fit_transform(X[:,1])

labelencoder_X_2= LabelEncoder()
X[:,2]= labelencoder_X_2.fit_transform(X[:,2])

onehotencoder= OneHotEncoder(categorical_features= [1])
X= onehotencoder.fit_transform(X).toarray()

X= X[:,1:]

E:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
E:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [86]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=.2, random_state=0)

In [108]:
y_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [87]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [88]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [89]:
import keras
from keras.models import Sequential
from keras.layers import Dense

### Initializing the ANN

In [90]:
classifier= Sequential()

### Adding the input layer and first Hidden layer

In [91]:
classifier.add(Dense(output_dim= 6, init='uniform',activation= 'relu',input_dim= 11))

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


### Adding the second hidden layer

In [92]:
classifier.add(Dense(output_dim= 6, init='uniform',activation= 'relu'))

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


### Adding output layer

In [93]:
classifier.add(Dense(output_dim= 1, init='uniform',activation= 'sigmoid'))

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


### Compiling the ANN

In [94]:
classifier.compile(optimizer='adam',loss= 'binary_crossentropy',metrics=['accuracy'])

### Making the predictions and evaluating the model

In [96]:
classifier.fit(X_train,y_train,batch_size=10,nb_epoch=100)

Epoch 1/100
 640/8000 [=>............................] - ETA: 1s - loss: 0.3637 - accuracy: 0.8594

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


8000/8000 [==============================] - 2s 222us/step - loss: 0.3447 - accuracy: 0.8604
Epoch 2/100
8000/8000 [==============================] - 2s 215us/step - loss: 0.3447 - accuracy: 0.8576
Epoch 3/100
8000/8000 [==============================] - 2s 232us/step - loss: 0.3442 - accuracy: 0.8601
Epoch 4/100
8000/8000 [==============================] - 2s 246us/step - loss: 0.3438 - accuracy: 0.8601
Epoch 5/100
8000/8000 [==============================] - 2s 214us/step - loss: 0.3441 - accuracy: 0.8614
Epoch 6/100
8000/8000 [==============================] - 2s 225us/step - loss: 0.3451 - accuracy: 0.8589
Epoch 7/100
8000/8000 [==============================] - 2s 216us/step - loss: 0.3431 - accuracy: 0.8596
Epoch 8/100
8000/8000 [==============================] - 2s 222us/step - loss: 0.3439 - accuracy: 0.8601
Epoch 9/100
8000/8000 [==============================] - 2s 228us/step - loss: 0.3435 - accuracy: 0.8591
Epoch 10/100
8000/8000 [==============================] - 2s 215us/

8000/8000 [==============================] - 1s 164us/step - loss: 0.3381 - accuracy: 0.8643
Epoch 79/100
8000/8000 [==============================] - 1s 167us/step - loss: 0.3380 - accuracy: 0.8640
Epoch 80/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3371 - accuracy: 0.8636
Epoch 81/100
8000/8000 [==============================] - 1s 151us/step - loss: 0.3373 - accuracy: 0.8624
Epoch 82/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.3370 - accuracy: 0.8634
Epoch 83/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.3373 - accuracy: 0.8608
Epoch 84/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.3363 - accuracy: 0.8614
Epoch 85/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.3361 - accuracy: 0.8625
Epoch 86/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.3359 - accuracy: 0.8634
Epoch 87/100
8000/8000 [==============================] - 1

In [109]:
y_pred= classifier.predict(X_test)
y_pred= (y_pred > 0.5)

In [110]:
y_pred[:20]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False]])

In [111]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_pred)

In [112]:
cm

array([[1497,   98],
       [ 190,  215]], dtype=int64)

In [113]:
(1497+215)/2000

0.856