In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [53]:
dataset= pd.read_csv(("C:\\Users\\HP\\Downloads\\Python ML\\Machine Learning A-Z Template Folder\\Part 2 - Regression\\Section 5 - Multiple Linear Regression\\50_Startups.csv"))

In [54]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [55]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
R&D Spend          50 non-null float64
Administration     50 non-null float64
Marketing Spend    50 non-null float64
State              50 non-null object
Profit             50 non-null float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [56]:
X=dataset.iloc[:,0:4].values
y=dataset.iloc[:,-1].values

In [57]:
X[:5,0:4]

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida']], dtype=object)

In [58]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [59]:
dataset.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [60]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X= LabelEncoder()
onehotencoder= OneHotEncoder(categorical_features=[3])

X[:,3]=labelencoder_X.fit_transform(X[:,3])
X=onehotencoder.fit_transform(X).toarray()



E:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
E:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [61]:
#Avoiding Dummy variable Trap

X[:5,1:]

array([[0.0000000e+00, 1.0000000e+00, 1.6534920e+05, 1.3689780e+05,
        4.7178410e+05],
       [0.0000000e+00, 0.0000000e+00, 1.6259770e+05, 1.5137759e+05,
        4.4389853e+05],
       [1.0000000e+00, 0.0000000e+00, 1.5344151e+05, 1.0114555e+05,
        4.0793454e+05],
       [0.0000000e+00, 1.0000000e+00, 1.4437241e+05, 1.1867185e+05,
        3.8319962e+05],
       [1.0000000e+00, 0.0000000e+00, 1.4210734e+05, 9.1391770e+04,
        3.6616842e+05]])

In [62]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=.2,random_state=0)

In [63]:
#fitting multiple linear regression to training set

from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor=regressor.fit(X_train,y_train)

In [64]:
# Predict te test result
y_pred=regressor.predict(X_test)

In [65]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [66]:
y_pred

array([103015.20159796, 132582.27760815, 132447.73845173,  71976.09851258,
       178537.48221051, 116161.24230163,  67851.69209676,  98791.73374689,
       113969.43533011, 167921.06569547])

### Building Optimal model using Backword Elimination( p-value and Adusted R sqaure)

In [69]:
import statsmodels.api as sm
def backwardElimination(X,SL):
    numVars= len(X[0])
    temp=np.zeros((50,6)).astype(int)
    for i in range(0,numVars):
        regressor_OLSi= sm.OLS(y,X).fit()
        maxVar=max(regressor_OLSi.pvalues).astype(float)
        adjR_before= regressor_OLSi.rsquared_adj.astype(float)
        if maxVar > SL:
            for j in range(0,numVars-i):
                if(regressor_OLSi.pvalues[j].astype(float)==maxVar):
                   temp[:,j]=X[:,j]
                   X=np.delete(X,j,1)
                   tmp_regressor=sm.OLS(y,X).fit()
                   adjR_after=tmp_regressor.rsquared_adj.astyep(float)
                   if (adjR_before >= adjR_after):
                        X_rollback=np.hstack((X,temp[:,[0,j]]))
                        X_rollback=np.delete(X_rollback,j,1)
                        print(regressor_OLSi.summary())
                        return X_rollback
                   else:
                        continue
regressor_OLSi.summary()
return X

SL=0.05
X_opt=X[:,[0,1,2,3,4,5]]
X_Modeled=backwardElimination(X_opt,SL)
                

NameError: name 'regressor_OLSi' is not defined